### ISSUE TITLE
Include Coil sensitivity information in ISMRMRD file

### ISSUE THREAD

**Issue by chandnisp77** [ismrmrd/ismrmrd#102]
Hello all,

I use `siemens_to_ismrmrd` for coverting a TSE sequence siemens data file `meas_MID190_t2_tse_tra_FID1092395.dat`  to ISMRMRD format. The siemens data folder I received has other files like
meas_MID178_AdjFre_FID1092383.dat
meas_MID179_AdjTra_FID1092384.dat
meas_MID181_AdjCoilSens_FID1092386.dat
I think `meas_MID181_AdjCoilSens_FID1092386.dat` is for generating coil sensitivity maps. I understand that ISMRMRD has flags like `ISMRMRD_ACQ_IS_PARALLEL_CALIBRATION` and `ISMRMRD_ACQ_IS_PARALLEL_CALIBRATION_AND_IMAGING` to set whether an acquisition refers to coil calibration data. How can I include coil calibration acquisitions from meas_MID181_AdjCoilSens_FID1092386.dat to TSE sequence .h5 file. Is it done through programmes or can it be handled by the converter itself through some options?

Thanks.

**Comment by hansenms** [comment]
I will be closing this issue. The way to do this is to have two ISMRMRD files, one for the coil sensitivity data and one for the measurement itself. One should depend on the other.
