### ISSUE TITLE
the reconstructed image size is larger than k-space data matrix size

### ISSUE THREAD

**Issue by JZhaoCH** [ismrmrd/ismrmrd#127]
Hello, I downloaded the "Stanford FullySampled 3D FSE Knees" data set from mridata.org, it's in ISMRMRD data format. I used the matlab code `test_recon_dataset.m` to reconstruct image , and found that the `encoding.encodedSpace.matrixSize.x` is larger than `encoding.reconSpace.matrixSize.x`, the matrix size of kspace data is `320*320`, and the reconstructed image is `512*512`.

 I don't understand why the reconstruted size is larger than the kspace data size, and an error occurred in the `test_recon_dataset.m` , because the code can't deal with this situation.

**Comment by ghisvail** [comment]
It's quite standard to reconstruct an image with dimensions set to the next power of two of the encoding matrix (which should eventually be zero-padded). FFTs are faster at dealing with power-of-2 matrices, at the price of some interpolation in the reconstructed image.

**Comment by ghisvail** [comment]
Looking at the `test_recon_dataset.m` script, it looks like it deals with the opposite case. Say for instance an encoding space of 512x320, reconstructed to 320x320 by FFT then cropping in the image space.

In your specific case, it sounds like all you'd need is to zero fill your k-space to 512x512 and then perform an FFT without cropping.

**Comment by JZhaoCH** [comment]
@ghisvail Hi, Ghislain, and I have a question, how to insert zero, like the matlab function ifft2, it pads k-space data with trailing zeros to form an 512-by-512 matrix. Or should I create the 512-by-512 zero matrix firstly, and put the k-space data in the center of zero matrix to form an 512-by-512 matrix.

**Comment by JZhaoCH** [comment]
@ghisvail Hi, Ghislain, thanks for your comment😃. And I have a question, how to insert zero, like the matlab function ifft2, it pads k-space data with trailing zeros to form an 512-by-512 matrix.
Or should I create the 512-by-512 zero matrix firstly, and put the k-space data in the center of zero matrix to form an 512-by-512 matrix.

**Comment by ghisvail** [comment]
The latter. Just calculate the boundaries of your k-space data within the 512x512 matrix like it's done [here](https://github.com/ismrmrd/ismrmrd/blob/601f014dc05907eac8bf0dc628ad43d9dbbdc59c/examples/matlab/test_recon_dataset.m#L142).

**Comment by ghisvail** [comment]
Have you got a link for the dataset you mentioned in the opening post?

**Comment by JZhaoCH** [comment]
@ghisvail 
The download link of the dataset is https://mridata-assets.s3.amazonaws.com/media/52c2fd53-d233-4444-8bfd-7c454240d314.h5 
or you can find it in the http://mridata.org/list?project=Stanford%20Fullysampled%203D%20FSE%20Knees
