### ISSUE TITLE
Partial Fourier data representation

### ISSUE THREAD

**Issue by roshtha** [ismrmrd/ismrmrd#131]
Hello all,

I have a T2 TSE raw data file from Siemens 1.5 T machine which I convert to ISMRMRD .h5 format using [siemens_to_ismrmrd](https://github.com/ismrmrd/siemens_to_ismrmrd). 

The encoding information in ISMRMRD header:
```<encoding>
     <encodedSpace>
			<matrixSize>
				<x>512</x>
				<y>228</y>
				<z>1</z>
			</matrixSize>
			<fieldOfView_mm>
				<x>460.000000</x>
				<y>204.542404</y>
				<z>7.500000</z>
			</fieldOfView_mm>
		</encodedSpace>
		<reconSpace>
			<matrixSize>
				<x>512</x>
				<y>432</y>
				<z>1</z>
			</matrixSize>
			<fieldOfView_mm>
				<x>230.000000</x>
				<y>194.063004</y>
				<z>5.000000</z>
			</fieldOfView_mm>
		</reconSpace>
		<encodingLimits>
			<kspace_encoding_step_1>
				<minimum>0</minimum>
				<maximum>188</maximum>
				<center>94</center>
			</kspace_encoding_step_1>
			<kspace_encoding_step_2>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</kspace_encoding_step_2>
			<average>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</average>
			<slice>
				<minimum>0</minimum>
				<maximum>18</maximum>
				<center>0</center>
			</slice>
			<contrast>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</contrast>
			<phase>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</phase>
			<repetition>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</repetition>
			<set>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</set>
			<segment>
				<minimum>0</minimum>
				<maximum>0</maximum>
				<center>0</center>
			</segment>
		</encodingLimits>
		<trajectory>cartesian</trajectory>
		<parallelImaging>
			<accelerationFactor>
				<kspace_encoding_step_1>1</kspace_encoding_step_1>
				<kspace_encoding_step_2>1</kspace_encoding_step_2>
			</accelerationFactor>
			<calibrationMode>other</calibrationMode>
			<interleavingDimension>other</interleavingDimension>
		</parallelImaging>
	</encoding>
```
[phatom_ismrmrd.txt](https://github.com/ismrmrd/ismrmrd/files/3121110/phatom_ismrmrd.txt)

The image is acquired at a matrix size of 512 x 228 x 1 and to be reconstructed at a matrix size of 512 x 432 x 1. The “encodingLimits” section shows the ky center 94 and the minimum and maximum ky values (0 and 188 respectively). 

I think this is a partial Fourier acquisition where only 189 out of 228 PE lines acquired. When I plot acquired 512x189 kspace data in matlab, I get the following
![Untitled](https://user-images.githubusercontent.com/5310634/56805297-38b69500-6846-11e9-8231-e91aea4688f6.png) Fig1

I understand with partial fourier, only half of k-space data is collected and the other half can be estimated using zero filling or by utilizing conjugate symmetry property.  The encoding matrix size 512x228 will be created with  189 lines of acquired data and rest will be zero filled. Then the kspace should be somewhat like 
![images](https://user-images.githubusercontent.com/5310634/56805456-c0040880-6846-11e9-9590-211096fce24d.jpeg) Fig2

But with the data from the scanner, I think the conjugate symmetry already exists across origin of kspace (Fig 1). So my question is whether this data set represent a partial fourier acquisition? How can I apply conjugate symmetry for a reconstruction?

Thanks all.

**Comment by ghisvail** [comment]
Le ven. 26 avr. 2019 à 13:56, thara <notifications@github.com> a écrit :

> Hello all,
>
> I have a T2 TSE raw data file from Siemens 1.5 T machine which I convert
> to ISMRMRD .h5 format using siemens_to_ismrmrd
> <https://github.com/ismrmrd/siemens_to_ismrmrd>.
>
> The encoding information in ISMRMRD header:
>
>      <encodedSpace>
>
> 			<matrixSize>
>
> 				<x>512</x>
>
> 				<y>228</y>
>
> 				<z>1</z>
>
> 			</matrixSize>
>
> 			<fieldOfView_mm>
>
> 				<x>460.000000</x>
>
> 				<y>204.542404</y>
>
> 				<z>7.500000</z>
>
> 			</fieldOfView_mm>
>
> 		</encodedSpace>
>
> 		<reconSpace>
>
> 			<matrixSize>
>
> 				<x>512</x>
>
> 				<y>432</y>
>
> 				<z>1</z>
>
> 			</matrixSize>
>
> 			<fieldOfView_mm>
>
> 				<x>230.000000</x>
>
> 				<y>194.063004</y>
>
> 				<z>5.000000</z>
>
> 			</fieldOfView_mm>
>
> 		</reconSpace>
>
> 		<encodingLimits>
>
> 			<kspace_encoding_step_1>
>
> 				<minimum>0</minimum>
>
> 				<maximum>188</maximum>
>
> 				<center>94</center>
>
> 			</kspace_encoding_step_1>
>
> 			<kspace_encoding_step_2>
>
> 				<minimum>0</minimum>
>
> 				<maximum>0</maximum>
>
> 				<center>0</center>
>
> 			</kspace_encoding_step_2>
>
> 			<average>
>
> 				<minimum>0</minimum>
>
> 				<maximum>0</maximum>
>
> 				<center>0</center>
>
> 			</average>
>
> 			<slice>
>
> 				<minimum>0</minimum>
>
> 				<maximum>18</maximum>
>
> 				<center>0</center>
>
> 			</slice>
>
> 			<contrast>
>
> 				<minimum>0</minimum>
>
> 				<maximum>0</maximum>
>
> 				<center>0</center>
>
> 			</contrast>
>
> 			<phase>
>
> 				<minimum>0</minimum>
>
> 				<maximum>0</maximum>
>
> 				<center>0</center>
>
> 			</phase>
>
> 			<repetition>
>
> 				<minimum>0</minimum>
>
> 				<maximum>0</maximum>
>
> 				<center>0</center>
>
> 			</repetition>
>
> 			<set>
>
> 				<minimum>0</minimum>
>
> 				<maximum>0</maximum>
>
> 				<center>0</center>
>
> 			</set>
>
> 			<segment>
>
> 				<minimum>0</minimum>
>
> 				<maximum>0</maximum>
>
> 				<center>0</center>
>
> 			</segment>
>
> 		</encodingLimits>
>
> 		<trajectory>cartesian</trajectory>
>
> 		<parallelImaging>
>
> 			<accelerationFactor>
>
> 				<kspace_encoding_step_1>1</kspace_encoding_step_1>
>
> 				<kspace_encoding_step_2>1</kspace_encoding_step_2>
>
> 			</accelerationFactor>
>
> 			<calibrationMode>other</calibrationMode>
>
> 			<interleavingDimension>other</interleavingDimension>
>
> 		</parallelImaging>
>
> 	</encoding>
>
>
> phatom_ismrmrd.txt
> <https://github.com/ismrmrd/ismrmrd/files/3121110/phatom_ismrmrd.txt>
>
> The image is acquired at a matrix size of 512 x 228 x 1 and to be
> reconstructed at a matrix size of 512 x 432 x 1. The “encodingLimits”
> section shows the ky center 94 and the minimum and maximum ky values (0 and
> 188 respectively).
>
> I think this is a partial Fourier acquisition where only 189 out of 228 PE
> lines acquired. When I plot acquired 512x189 kspace data in matlab, I get
> the following
> [image: Untitled]
> <https://user-images.githubusercontent.com/5310634/56805297-38b69500-6846-11e9-8231-e91aea4688f6.png>
> Fig1
>
> I understand with partial fourier, only half of k-space data is collected
> and the other half can be estimated using zero filling or by utilizing
> conjugate symmetry property.
>
I would recommend reading about the homodyne reconstruction.

https://www.google.com/url?q=https://users.fmrib.ox.ac.uk/~karla/reading_group/lecture_notes/Recon_Pauly_read.pdf&sa=U&ved=2ahUKEwjJrPCf_-_hAhUpD2MBHYLgCRIQFjAHegQIABAB&usg=AOvVaw1W4rNw_IV5RIJ4yGsvBt4_

The encoding matrix size 512x228 will be created with 189 lines of acquired

**Comment by tharagireesh** [comment]
From kspace plot,  I think acquired 512 x 189 data itself is a full kspace. But with ISMRMRD conventions, as the encodedSpace.y size is 228, the data should be of partial fourier. But I could not see partial fourier in acquired data. I would like know whether the above shown ISMRMRD header file represent a partial fourier acquisition?

Thanks.

**Comment by ghisvail** [comment]
> From kspace plot, I think acquired 512 x 189 data itself is a full kspace.

```xml
<kspace_encoding_step_1>
  <minimum>0</minimum>
  <maximum>188</maximum>
  <center>94</center>
</kspace_encoding_step_1>
```
The above metadata look consistent with a fully-sampled matrix composed of 189 phase encoding lines.

```xml
<matrixSize>
  <x>512</x>
  <y>228</y>
  <z>1</z>
</matrixSize>
```

But these suggest a different encoding matrix.

> I would like know whether the above shown ISMRMRD header file represent a partial fourier acquisition?

Try the reconstruction and you should get your answer. If a straight DFT from the 512x189 yields a satisfactory image, then you don't have partial Fourier and just need to zero-fill accordingly. If not, then you'd have to consider your center is not 94 but 114 and apply an homodyne reconstruction.

**Comment by tharagireesh** [comment]
Thanks for the answer. 

I tried reconstruction with FFT, Zero fill FFT and homodyne and here are the results.

A straight DFT from 512x189 gives an image which lost its image aspect ratio.

``` 
% phantom_kspace of size 512x189
figure('name','no zero filled kspace');imshow(log((phantom_kspace)),[]);
no_zero_fill_img_data =  ifftshift(fft(phantom_kspace,[],1),1);
no_zero_fill_img_data = ifftshift(fft(no_zero_fill_img_data,[],2),2);
figure('name','no zero filled image');imshow(abs(no_zero_fill_img_data),[])
```
![nozerofill](https://user-images.githubusercontent.com/5310634/57271316-a49dc680-70ac-11e9-8f93-bb2b28dc6114.png)

When I zero-fill data to 512x228, gives an image 

```
% phantom_kspace of size 512x228 (zero filled)
figure('name','zero filled kspace');imshow(log((phantom_kspace)),[]);
phantom_kspace =  ifftshift(fft(phantom_kspace,[],1),1);
phantom_kspace = ifftshift(fft(phantom_kspace,[],2),2);
figure('name','zero filled image');imshow(abs(phantom_kspace),[])
```

![zerofill](https://user-images.githubusercontent.com/5310634/57271352-cd25c080-70ac-11e9-99f5-12d9c6777a8e.png)

I then apply homodyne reconstruction (I use code from https://in.mathworks.com/matlabcentral/fileexchange/1114-pifft) 

```
% phantom_kspace of size 512x189 
figure('name','kspace for homodyne');imshow(log((phantom_kspace)),[]);
% Frequency Encode direction is assumed to be the longer direction
[Nf Npp ] = size(phantom_kspace);
% Number of phase encodes in the full k-space
Np = 228; 
% Number of high frequency phase encodes
NH = Np-Npp;
% NUmber of low frequency phase encodes
NL = Npp - NH;
% Row indices of high and low frequency lines
HFind = 1:NH;
LFind = (NH+1):(NH+NL);
% Create weighting window
%
% It multiplies all un-partnered high frequency lines by 2.0
% Low frequency lines are multiplied by a ramp that approaches 
% zero at the zero-padded edge of k-space.  The weighting
% factors of two partnered low frequency lines should have a 
% sum of 2.0
w = zeros(1,Np);
w(:,HFind) = 2;
rstep = 2/(NL+1);
w(:,LFind) = [(2-rstep):-rstep:rstep];
% Create weighted partial k-space
HFksp = zeros(Nf,Np);
HFksp(:,1:Npp)=phantom_kspace;
HFksp = HFksp.*repmat(w,Nf,1);
figure('name','Weighted kspace');imshow(log((HFksp)),[]);
% Create Low Frequency k-space 
LFksp = zeros(Nf,Np);
LFksp(:,LFind) = phantom_kspace(:,LFind);
figure('name','Low Frequency kspace');imshow(log((LFksp)),[]);
% Low frequency image
Rc = ifftshift(fft(LFksp,[],1),1);
Rc = ifftshift(fft(Rc,[],2),2);
% Unsynchronous image
Ic = ifftshift(fft(HFksp,[],1),1);
Ic = ifftshift(fft(Ic,[],2),2);
% Synchronous image
Is = Ic.*exp(-i*angle(Rc));
% Demodulated image
m = real(Is);
figure('name','Homodyne image');imshow(abs(m),[])
````

![homodyne](https://user-images.githubusercontent.com/5310634/57271542-7a98d400-70ad-11e9-81c1-559da0a1c15b.png)


What I undertood from http://81bones.net/mri/mri_advRecon2.pdf and http://www.mecs-press.org/ijigsp/ijigsp-v7-n7/IJIGSP-V7-N7-6.pdf is that partial kspace will have a symmetrically sampled region around central k=0 line and asymmetrically sampled high frequency region. My understanding is that symmetrically sampled region is used for generating low resolution image and asymmetric high frequency region is used for preweighting k-space. The kspace used in above shown homodyne code (`phantom_kspace`) has no asymmetrically sampled area. Hence I feel homodyne reconstruction does not fit this k-space. 

How can I proceed with homodyne reconstruction for this k-space?  

Thanks.
