### ISSUE TITLE
Memory leak in ISMRMRD::Acquisition::operator=()

### ISSUE THREAD

**Issue by johannesmayer** [ismrmrd/ismrmrd#135]
When assigning an existing object of type `ISMRMRD::Acquisition` in loop constructions to temporary variable there seems to be a memory leak.

The code below quickly eats up 50 GB of RAM if the variable `construct_inside_loop` is set to `false` and no problems arise if set to `true`.

````
bool construct_inside_loop = false;

size_t num_iterations = 1000;

size_t num_acquis = 256*128;
uint16_t num_samples = 192;
uint16_t num_channels = 32;
		
ISMRMRD::Acquisition acq(num_samples, num_channels);

if( construct_inside_loop )
{
for(size_t i=0; i<num_iterations; i++)
{
    std::cout << "loopindex i " << i <<std::endl;

    for(size_t i_acq=0; i_acq<num_acquis; i_acq++)
    {	
        ISMRMRD::Acquisition temp_acq;
        temp_acq = acq; 
    }
}} 
else
{
for(size_t i=0; i<num_iterations; i++)
{
    std::cout << "loopindex i " << i <<std::endl;

    ISMRMRD::Acquisition temp_acq;
    for(size_t i_acq=0; i_acq<num_acquis; i_acq++)
    {	
        temp_acq = acq; 
    } 
}}
```` 

There has been some discussion on the matter in our group CCPPETMR/SIRF#204. However, it has been aimed at finding the problem in our code which we eventually didn't.

**Comment by dchansen** [comment]
Thank you for finding this! We do run leak checks on Gadgetron, but I guess we never reassign any Acquisitions. It should be fixed in the latest commit.
