### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by KrisThielemans** [ismrmrd/ismrmrd#136]
hi. it seems a number of bugs that caused https://github.com/CCPPETMR/SIRF problems have been fixed. thanks! Would you consider creating a new release such that we can refer to that?

**Comment by dchansen** [comment]
Sure thing. 1.4.1 created.

**Comment by KrisThielemans** [comment]
wonderful. thanks!

**Comment by evgueni-ovtchinnikov** [comment]
seems to work fine
