### ISSUE TITLE
Copying XML header from input data to images

### ISSUE THREAD

**Issue by rijobro** [ismrmrd/ismrmrd#138]
This isn't an issue per say, so feel free to close; I was just looking for an answer.

We noticed that raw MR data contains an XML header. This contains useful information, such as patient orientation (HFS etc.). So as of https://github.com/CCPPETMR/SIRF/pull/445, we copy this header from the input data to the reconstructed images. Is this a bad idea? We notice that it's not done in ISMRMRD nor Gadgetron.

As a slightly related question, are `slice_dir`, `read_dir` and `phase_dir` in a patient or scanner coordinate system?

**Comment by dchansen** [comment]
There is nothing wrong with saving the XML header with the reconstructed images. In Gadgetron the needed info is usually stored as metadata on the image, but you could do it either way.

As for slice_dir, read_dir and phase_dir, I am actually unsure about the coordinate system, but I do know it's the same as the aflQuaternion in the Siemens metadata.

**Comment by marcsous** [comment]
Regarding read_dir, I notice it does not change sign when reversing the readout gradient (or when setting the Siemens MDH_REFLECT flag). I'm just wondering how we can deduce the readout direction - or at least a sign change in read_dir - for the case of bipolar gradient acquisitions, e.g. multiecho with bipolar readouts.
