### ISSUE TITLE
Cannot install in windows (Could NOT find Boost)

### ISSUE THREAD

**Issue by aghaeifar** [ismrmrd/ismrmrd#139]
Hi

I am a windows user and trying to install ISMRMRD according the guideline provided in 
[](https://ismrmrd.github.io/#windows-installation)

Seems there is a problem that cmake-gui can't properly recognize boost library. I changed the cmakelists.txt to add the path of FFTW3 and Boost as follows:

```
set(Boost_DEBUG 1)
SET(BOOST_ROOT "C:/Users/aaghaeifar/Downloads/ismrmd/boost_1_71_0/install_path")
SET(Boost_INCLUDE_DIR "C:/Users/aaghaeifar/Downloads/ismrmd/boost_1_71_0/install_path/include")
SET(BOOST_INCLUDEDIR "C:/Users/aaghaeifar/Downloads/ismrmd/boost_1_71_0/install_path/include")
SET(Boost_LIBRARY_DIRS "C:/Users/aaghaeifar/Downloads/ismrmd/boost_1_71_0/install_path/lib")
SET(BOOST_LIBRARYDIR "C:/Users/aaghaeifar/Downloads/ismrmd/boost_1_71_0/install_path/lib")
SET(FFTW3_INCLUDE_DIR "C:/Users/aaghaeifar/Downloads/ismrmd/fftw-3.3.2-dll64")
SET(FFTW3F_LIBRARY "C:/Users/aaghaeifar/Downloads/ismrmd/fftw-3.3.2-dll64/libfftw3f-3.lib")
```

However, seems something is still missed. Here is the output message:

```
Could NOT find Boost (missing: program_options) (found suitable version "1.71.0", minimum required is "1.43")
FFTW3 WINDOWS libraries: C:/Users/aaghaeifar/Downloads/ismrmd/fftw-3.3.2-dll64/libfftw3f-3.lib
Found FFTW3: C:/Users/aaghaeifar/Downloads/ismrmd/fftw-3.3.2-dll64/libfftw3f-3.lib  
FFTW3 or Boost NOT Found, cannot build utilities
```

Any suggestion or comment? Anyone has recently tried to install ismrmrd in windows?
Thanks.

**Comment by Aghaeifar** [comment]
Finally worked! 
Found the solution [here](https://stackoverflow.com/questions/13280823/cmake-is-not-finding-boost).
I built Boost using _bjam_ with `link=static threading=multi`

so just added following line to cmakelists.txt and cmake was successful 

`set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)`
