### ISSUE TITLE
trajectory_dimensions : Incohenrence between MRD and gadgetron

### ISSUE THREAD

**Issue by aTrotier** [ismrmrd/ismrmrd#160]
For non-cartesian acquisition, it is written in the [documentation](https://ismrmrd.github.io/) : 

> float* traj_;            //Trajectory, elements = head_.trajectory_dimensions*head_.number_of_samples
>                          //   [kx,ky,kx,ky.....]        (for head_.trajectory_dimensions = 2)
>                          //   [kx,ky,kz,kx,ky,kz,.....] (for head_.trajectory_dimensions = 3)

However in Gadgetron, for most of the gadgets, the field trajectory_dimensions  = 3 means 
-> 2D trajectory + density compensation function

**Comment by hansenms** [comment]
Not sure this is really an "inconsistency" as such. Those trajectory dimensions were never defined to have specific semantic meaning (which is a problem), but they can be used for anything really; it could also be something that has nothing to do with k-space. So I think the only slight problem here is that maybe the comments should have read `// e.g. [kx,ky,kz,kx,ky,kz,.....] ...`.
