### ISSUE TITLE
Incorrect indexing in channel mask helper function

### ISSUE THREAD

**Issue by naegelejd** [ismrmrd/ismrmrd#17]
In `ismrmrd_set_channel_on`, the [indexing to calculate the bitmask and offset](https://github.com/ismrmrd/ismrmrd/blob/21fae3c85d6bb2d0a959e14fe2b6398126114547/libsrc/ismrmrd.c#L531-L532) are incorrect. They should divide by `64`, not `ISMRMRD_CHANNEL_MASKS`. See `ismrmrd_set_channel_off` for a [correct example](https://github.com/ismrmrd/ismrmrd/blob/21fae3c85d6bb2d0a959e14fe2b6398126114547/libsrc/ismrmrd.c#L543-L544).

**Comment by inati** [comment]
Did I just stupidly write this two different ways?!?

**Comment by naegelejd** [comment]
I wouldn't have found this without unit tests: https://github.com/naegelejd/ismrmrd/tree/unit-tests. See Travis-CI link in README.

**Comment by inati** [comment]
Nice!
