### ISSUE TITLE
Add patientSize into SubjectInformation

### ISSUE THREAD

**Issue by achataigner** [ismrmrd/ismrmrd#177]
Would it be possible to add patientSize into SubjectInformation ?
Is there some information I need to know before proposing a pull request ?

**Comment by hansenms** [comment]
What would `patientSize` mean? Is this a patient weight (which is there already) or something else?

**Comment by achataigner** [comment]
Its meaning is the same as dicom tag PatientSize : height of the patient :)

**Comment by hansenms** [comment]
Then I think it should be called `patientHeight_m` to be consistent with the other naming that is in there. It would need to be properly added to the schema and the minor version of the library will have to be incremented according the current conventions.

**Comment by achataigner** [comment]
pr waiting for review: https://github.com/ismrmrd/ismrmrd/pull/178
