### ISSUE TITLE
find_dependency(HDF5) in config could be conditional

### ISSUE THREAD

**Issue by KrisThielemans** [ismrmrd/ismrmrd#183]
I believe that these lines should be included only if `USE_HDF5_DATASET_SUPPORT=ON`
https://github.com/ismrmrd/ismrmrd/blob/feb3040f5d65148a45d84fd0125091a41138a2c6/cmake/ISMRMRDConfig.cmake.in#L44-L49

If CMake version >= 3.9, it doesn't matter too much as `find_dependency` [will forward](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html) the `REQUIRED`. So the worst thing that can happen is that we will be searching for HDF5 when it actually isn't used.

If CMake version < 3.9, the `find_package` statement should have a `REQUIRED` when  `USE_HDF5_DATASET_SUPPORT=ON`.

**Comment by hansenms** [comment]
PR please.
