### ISSUE TITLE
need to use target_include_directories for HDF5 (and others)

### ISSUE THREAD

**Issue by KrisThielemans** [ismrmrd/ismrmrd#184]
https://github.com/ismrmrd/ismrmrd/blob/4c453a2a5596023b21931b6c5ad01201ceb6acf3/CMakeLists.txt#L139-L140
should use `target_include_directories`, such that dependency on HDF5 gets sorted for anyone using ISMRMRD.

**Comment by hansenms** [comment]
PR please
