### ISSUE TITLE
MSVC C89 support

### ISSUE THREAD

**Issue by naegelejd** [ismrmrd/ismrmrd#20]
In order to support VS2012 we have historically ensured that the C portion of ISMRMRD is valid C89. Since we no longer have a VS2012 buildbot, we should probably change the Linux/OS X compiler flags to `-std=c89 -pedantic` to ensure VS2012 compatibility.

It may be a good idea to revisit this issue in the future because the ability to use C99 would be ideal.

**Comment by ghisvail** [comment]
Philips uses VS2008 for their recon machine, so as long as this compiler remains supported I am cool with whatever you guys decide.

**Comment by naegelejd** [comment]
One potential option is to figure out how to ensure that all of ISMRMRD (C and C++ files) is treated as C++ code by MSVC ([apparently with the command line option `/TC`](https://msdn.microsoft.com/en-us/library/032xwy55%28v=vs.90%29.aspx)) since C++ supports the C99 features we're currently avoiding.

**Comment by ghisvail** [comment]
What would you gain from C99 again ? use of complex type instead of float[2] ?

**Comment by inati** [comment]
@ghisvail we definitely don't have a VS2008 setup to test against.  That *should* handle proper C89 and in C++ mode *may* handle the C99 features we are avoiding (declaring variables in the middle of code and // style comments).  I like the intermediate fix of using GCC with the appropriate flag to check for C89 compatibility, but either way, we need someone who cares about older VS to test.

**Comment by naegelejd** [comment]
C++ mode *would* handle the missing C99 features but I agree with @inati  that the GCC `-std=c89` flag is sufficient, even in the long term. The primary feature we'd gain is intermingled declarations and code, which I will argue is critical. Also, everything listed [here](http://blogs.msdn.com/b/vcblog/archive/2013/07/19/c99-library-support-in-visual-studio-2013.aspx).
