### ISSUE TITLE
compilation problem on Windows VS 2022 and ninja: size_t

### ISSUE THREAD

**Issue by KrisThielemans** [ismrmrd/ismrmrd#217]
I'm getting a compilation problem as `size_t` is not defined.
```
C:\Users\krisf\Documents\devel\buildninja\SIRF-SuperBuild\sources\ISMRMRD\include\ismrmrd/ismrmrd.h(129): error C2061: syntax error: identifier 'ismrmrd_sizeof_data_type'
```
and many others. Weirdly, this doesn't happen when using the Visual Studio generator.

Currently there are the following lines
https://github.com/ismrmrd/ismrmrd/blob/bae6bcde22969d56e027de7497804520619b687c/include/ismrmrd/ismrmrd.h#L24-L36
I have no idea who is supposed to define `HAS_INT_TYPE`, but it isn't defined if I used either ninja or VS. So it uses these explicit defines, but they don't define `size_t`. It appears that when using the VS Generator, `size_t` is defined somehow, but not when using ninja.

These lines were introduced in the very first commit 10 years ago 8cd0ccdd36a47584bc5f912399fa09bc7589cb35, and then guarded with `HAS_INT_TYPE` in 8006a95cb23aae90430d82733d3a2ebad29f47fc, This looks very much outdated. I checked that everything works fine when I just do
```c++
 #include <stdint.h> 
 #include <stddef.h>     /* for size_t */ 
```
I don't know how old a compiler you want to support of course.

**Comment by dchansen** [comment]
Google and Sourcegraph suggest that "HAS_INT_TYPE" is not used in any open source project except ismrmrd. I suspect that `#ifndef` does nothing - and probably never has.  

We unfortunately need ismrmrd to work with relatively old compilers - including VS 2012. @kspaceKelvin can you confirm the exact version? And maybe test that just using the standard headers would be ok?

**Comment by KrisThielemans** [comment]
> I suspect that `#ifndef` does nothing - and probably never has.

agreed, but that means that those \#defines where used for `_MSC_VER` compilers, even recent ones.

**Comment by dchansen** [comment]
Looking further into this: 
It appears that VS 2008 did not have `stdint.h`, or indeed C99 conformance, so that is presumably the original culprit.
I think it might be reasonable for people to simply provide their own `stdint.h`  if their compiler does not come with one.
