### ISSUE TITLE
PugiXML was not found || Possible solution exists in a commit

### ISSUE THREAD

**Issue by Aditya-Tejaswi** [ismrmrd/ismrmrd#227]
**Describe the bug**
Error on Ubuntu version 20.04.5 LTS while installing the siemens_to_ismrmrd and philips_to_ismrmrd converters on the system. I tried after the latest fixes in the commit [0bc36e5](https://github.com/ismrmrd/ismrmrd/commit/0bc36e527322113db374b03f07fcc03f328311d0) and still faced the problem.

---
**To Reproduce**
1. Start with a fresh terminal in Ubuntu 20.04.5
2. Follow the steps for installation of the converters for Linux installations from the repositories: [https://github.com/ismrmrd/siemens_to_ismrmrd]() or [https://github.com/ismrmrd/philips_to_ismrmrd]().
3. After cloning the repository ``` $ git clone https://github.com/ismrmrd/ismrmrd.git``` and executing the steps:
 * ```$ cd ismrmrd ```
* ```$ mkdir build```
* ```$ cd build```
* ```$ cmake .. ```
I get the error:
```pthon
CMake Error at cmake/FindPugiXML.cmake:25 (message):
  PugiXML was not found.
Call Stack (most recent call first):
  CMakeLists.txt:215 (find_package)
```
---
**Logs/Screenshots**
![Screenshot from 2023-01-26 09-44-54](https://user-images.githubusercontent.com/71258200/214797145-15122b2f-5105-4630-97a7-ab7fa2df4d9f.png)

**System Information:**
 - OS: Linux, Ubuntu 20.04.5 LTS, also tried on Ubuntu version 18.04 and faced the same error

---
**A Workaround**
I tried installing the latest cmake version but that didn't work. I saw that the latest commit in this repository [0bc36e5](https://github.com/ismrmrd/ismrmrd/commit/0bc36e527322113db374b03f07fcc03f328311d0) and for modifications in ```  .github/workflows/ismrmrd_build.yml ```, the code was modified in line 28 and I just ran that line:
``` sudo apt-get -y install doxygen git-core graphviz libboost-all-dev libfftw3-dev libhdf5-serial-dev libxml2-utils libpugixml-dev``` in the terminal and then followed the steps from ``` $ cmake ..``` onwards and was able to install the siemens and philips converters.

So, in case, if anyone else is facing a similar problem with the ``` $ cmake ..``` command, you can try this for Linux systems. And cheers :beers: to the ISMRM team members :gem: for maintaing this repository :high_brightness:.

**Comment by roopchansinghv** [comment]
Thanks @Aditya-Tejaswi  - wondering if it's better to open up an issue on the various converters that depend on ISMRMRD, so we update the workflows and build instructions on those repos?

@hansenms @dchansen @xueh2 @kspaceKelvin - thoughts?

**Comment by hansenms** [comment]
Just skimming this here, is the issue "just" that we have removed PugiXML as bundled source from this repo and so it is now a dependency? And we need to update documentation accordingly?

**Comment by hansenms** [comment]
Install it: `sudo apt install libpugixml-dev`

**Comment by roopchansinghv** [comment]
For the longest while, ISMRMRD had a copy of the PguiXML sources within its own tree.  However, we have been running into security concerns with newer compilers and deprecated functions in our (much) older version of PugiXML.  So we removed Pugi from our source tree with commits [0bc36e5 (https://github.com/ismrmrd/ismrmrd/commit/0bc36e527322113db374b03f07fcc03f328311d0) and [f54a263](https://github.com/ismrmrd/ismrmrd/commit/f54a2637133f3cb7f30aea370c1a7cf82fd97a6a), with the caveat now that you would need to install PugiXML explicitly in your host OS/environment/container.

**Comment by xkdlsxm2** [comment]
Thanks you @hansenms and @roopchansinghv !!
