### ISSUE TITLE
Build failure: dependencies to outdated libpthread.so and libdl.so?

### ISSUE THREAD

**Issue by ChrisThe2nd** [ismrmrd/ismrmrd#240]
### Failed to make objects 
When trying to install ISMRMRD on Ubuntu 22.04, following the instructions given at [siemens_to_ismrmrd](https://github.com/ismrmrd/siemens_to_ismrmrd), the step `make` failed with the following errors: 
```
~/ismrmrd/build$ make
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpthread.so', needed by 'libismrmrd.so.1.13.7'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:171: CMakeFiles/ismrmrd.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```
and 
```
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libdl.so', needed by 'libismrmrd.so.1.13.7'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:171: CMakeFiles/ismrmrd.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

Same error message  repeated during building of the objects:
- utilities/ismrmrd_info
- utilities/ismrmrd_test_xml
- utilities/ismrmrd_read_timing_test
- utilities/ismrmrd_generate_cartesian_shepp_logan
- utilities/ismrmrd_recon_cartesian_2d
- utilities/ismrmrd_hdf5_to_stream
- utilities/ismrmrd_stream_to_hdf5
- utilities/ismrmrd_stream_recon_cartesian_2d
- examples/c/ismrmrd_c_example
- tests/test_ismrmrd
- tests/benchmark_dataset

On my system, the libraries libpthread.so and libdl.so are not available in 
/usr/lib/x86_64-linux-gnu/ 
but only libphtread.so.0 and libdl.so.2

Do I have the wrong libraries, i.e. versions, installed, although I followed the instructions: 
```
$ sudo apt-get install g++ cmake git
$ sudo apt-get install libboost-all-dev xsdcxx libxerces-c-dev libhdf5-serial-dev h5utils hdf5-tools libtinyxml-dev libxml2-dev libxslt1-dev libpugixml-dev
```

Thanks for your help!

**Comment by ChrisThe2nd** [comment]
I repeatedly tried to install ISMRMRD over the last few days.
I don't know why and how, but at some point, after clearing the outputs from CMake, and redoing the installation following the steps:
```
~/ismrmrd$ rm -rf build
~/ismrmrd$ mkdir build
~/ismrmrd$ cd build
~/ismrmrd/build$ cmake ..
~/ismrmrd/build$ make 
~/ismrmrd/build$ sudo make install
```
`make` suddenly succeeded. I checked the `build.make` files, and now they suddenly contained the correct links to the following external object files (libpthread & libdl):
```
In File: ~/ismrmrd/build/CMakeFiles/ismrmrd.dir/build.make, Line 210 ff.

# External object files for target ismrmrd
ismrmrd_EXTERNAL_OBJECTS =
[...]
libismrmrd.so.1.13.7: /usr/lib/x86_64-linux-gnu/libpthread.a
[...]
libismrmrd.so.1.13.7: /usr/lib/x86_64-linux-gnu/libdl.a
```

With this, I was able to install ISMRMRD and SIEMENS_TO_ISMRMRD successfully. 
However, the cause for the initial failure is still unclear to me. Unfortunately, I can not give a better solution than the steps above if the same happens to others.

**Comment by naegelejd** [comment]
This was likely an issue with cached CMake files. I don't think you should expect to encounter this issue again, but if you do, feel free to re-open.
