### ISSUE TITLE
Improve read only file support

### ISSUE THREAD

**Issue by inati** [ismrmrd/ismrmrd#29]
We should keep track of a status with the dataset so that you can fail cleanly on functions that try to write to a read-only file.  We should also have a way of warning the user when they have opened a read-only file.

**Comment by naegelejd** [comment]
A status flag makes sense but I'm not sure about warnings. I know we agreed to merge the PR from @isolovey-robarts, but it would make more sense for `ismrmrd_open_dataset` to take a flag that specifies whether to open it RW or RO. This is how **every** file-opening API works. This allows the user to *choose* how to open the file.

**Comment by inati** [comment]
That makes a lot of sense.  Let's do it.

**Comment by hansenms** [comment]
I agree, then we can just have the client open in RO mode and it should work regardless.

**Comment by naegelejd** [comment]
That makes sense. Does anyone have a preference for how to specify the file mode? e.g. to open in RW and create if it doesn't exist:

C and Python:
`ismrmrd_open_dataset(dset, "rw", true);`

POSIX:
`ismrmrd_open_dataset(dset, ISMRMRD_O_RDRW | ISMRMRD_O_CREAT)`

while the POSIX `open` style is uglier, I like how it's more explicit.

**Comment by inati** [comment]
Let’s talk this through a bit.

Looking at the HDF5 interface (thanks Oliver!) they split open and create

Create takes overwrite or preserve
H5F_ACC_TRUNC to overwrite an existing file or H5F_ACC_EXCL fails if the file already exists

Open takes read-write or read-only and fails if the file doesn’t already exist
H5F_ACC_RDWR or H5F_ACC_RDONLY

This makes sense as the space of options.  We have to combine the two functions into a single one so we end up with something that is unix-like (r,r+,w,w+,a,a+).

Thoughts?

**Comment by naegelejd** [comment]
Right but I only see three possible options:

- Open an existing dataset for reading only
- Open an existing dataset for reading/writing
- Create a new dataset for writing

The only other option would be to create a new dataset for reading only, which makes no sense.

**Comment by inati** [comment]
Right, but if you open an existing dataset to read/write, do you want to preserve its contents and append, or do you want to clobber it and start over?

**Comment by naegelejd** [comment]
How is that functionally different from
> Create a new dataset for writing

**Comment by naegelejd** [comment]
OK @inati and I discussed this more. We're going to shoot for the following functions:

- `ismrmrd_dataset_exists` - boolean for whether dataset already exists on disk
- `ismrmrd_create_dataset` - truncates existing dataset or creates a new one on disk
- `ismrmrd_open_dataset` - opens a dataset in **either** read-only or read-write mode

the user is responsible for checking whether the dataset exists before calling `ismrmrd_create_dataset`, in case they don't want to truncate existing data.
