### ISSUE TITLE
waveform extension

### ISSUE THREAD

**Issue by DANAJK** [ismrmrd/ismrmrd#32]
.... moving here from posts on the Gadgetron Hangout page: 

I agree we should keep the same fixed layout structure for waveforms as for the raw data, provided we can indicate the type of waveform (gradient, ECG etc). Either within this structure, or the XML header, there will also need to be an indication of the coordinate system  for a gradient waveform and whether or not gradients have been negated to account for 180's in the sequence. (Some applications will require the true gradients, others will need to account for the effective sign change of gradients caused by 180's during the diffusion preparation.)

It seems clear to me that physiology waveforms logically go with the raw k-space data in terms of needing the times synchronising. However, gradient waveforms used as preparation pulses, including diffusion weighting, are rarely analysed using the absolute timings. For example, the diffusion gradient waveform might be used to compute a b-value but it is not necessary to know exactly when this is played out relative to every raw  k-space line and so it feels more like a property of the scan as a whole, i.e. belonging in the XML header? 
If some waveforms are to go in the XML header, then I suggest they keep the same structure as those in the raw data to make reading easier.    

I hope I am making sense, it's possible I'm confused over how these waveforms are to be implemented. In ISMRMRD, following the XML header, there is the raw data section, and is it correct that within the raw section, there would be one waveform structure for every k-space readout?

**Comment by hansenms** [comment]
@DANAJK, some thoughts:

* Seems we agree that we should only have one fixed memory layout structure. It is a little unclear why and how you would want to force the same structure to be used in the XML header. How exactly would that work?

* I am a bit concerned about putting long waveform structures in the XML header, if we can avoid it. Is there any loss in generality or usability if waveforms are always in the raw data? On problem I can foresee is that applications that will need these waveforms will have to wait until they arrive in the stream. Another problem is how they would be generated in the first place, but that is probably a problem regardless. 

* Not sure about this negating business. Problem that when you really get into it and you need to estimate meaningful things from the waveforms, 180s are not really 180s, so you need the full waveforms. I am concerned about creating a bunch of shorthands and exceptions for specific applications. How exactly do you imagine this information being used. If the waveforms are not really used, except to calculate b values, why not just put the b values in there?

* I don't think there should be one waveform structure for every k-space readout. I imaging there could be an arbitrary number of either and in fact if we do this right, one could store a sequence (with no data) as an ISMRMRD file and use it as input for a Bloch simulator or something like that. 

I think we should probably chat on Friday's call (sorry I missed the one today).

**Comment by DANAJK** [comment]
First a related comment on Friday's discussion about including data with mixed types:
   Having separate arrays of different types, rather than one large byte array, might more naturally allow the inclusion of pulse sequence diagrams. The RFs could be in one array and the gradients in another. The gradients might not even need to be discretised very finely in time - just the slope times recorded. The challenge will be to make the timing and order clear.

For the waveform structure, if there can be an arbitrary number of waveforms, not necessarily the same as the number if k-space shots, then the waveform structure could go in the Data part of the HDF5 file rather than the XML. 

In some applications, one needs to consider the effect of the gradients on the spins and to also account for 180's as these affect the spins. In a pulse diagram, one can start at the excitation and move to later times, multiplying all the later gradients by -1 at each 180 encountered (hence the "negating" comment I made). I agree that this representation is not ideal from our perspective. If we adopt the multiple arrays method for storing stuff in HDF5, then as I say above, I think it will be easier for people to decode the pulse sequence and sort this for themselves.

**Comment by hansenms** [comment]
Just some quick comments. 

When we discussed have multiple array variables, I think we mean to separate it on the data type (complex, float, int, etc.). If you do RF and gradients, say, then they would probably have the same type (at least different gradients). So we would need a different way of separating it into different variables. How about this:
* We add a variable to the header which is a "data channel". Don't like that name, since it could be confused with actual receiver channels. So maybe "data_pipe". It would be an integer. 
* In the XML header, we could have a section where you can give meaning full names to each data pipe, i.e. ECG, RF, GZ, GY, etc., etc. 
* Each data pipe must contain only data of a certain type.
* Data from each data pipe goes into a separate variable in the HDF5

That way, we can support data from as many different acquisition sources as we would like. We don't have to use flags to indicate if this is k-space, gradient data, or other. It will stream perfectly fine in acquisition order. @naegelejd , @inati, @dchansen. Could you comment on this. This might work.
