### ISSUE TITLE
Disparate API - Acquisitions vs. Images

### ISSUE THREAD

**Issue by naegelejd** [ismrmrd/ismrmrd#33]
The `Acquisition` class [consists of functions returning non-const references to header fields](https://github.com/ismrmrd/ismrmrd/blob/516db3005b73d39d488bddef2865d6fd4a33584e/include/ismrmrd/ismrmrd.h#L490-L524) while the `Image` class [consists of proper "setters" and "getters"](https://github.com/ismrmrd/ismrmrd/blob/516db3005b73d39d488bddef2865d6fd4a33584e/include/ismrmrd/ismrmrd.h#L634-L693). This is confusing.

**Comment by naegelejd** [comment]
I'm going to go ahead and fix this in my 2.x branch.

**Comment by inati** [comment]
Good plan.
