### ISSUE TITLE
Add concept of data streams

### ISSUE THREAD

**Issue by naegelejd** [ismrmrd/ismrmrd#35]
ISMRMRD version 2.x will tentatively introduce the concept of "data streams", allowing for storing multiple types of acquisitions and wave forms in ISMRMRD datasets. Here are some notes on the specification **and** implementation details for discussion:
### XML Header

The ISMRMRD XML header schema will contain an additional section called "streams" containing an unlimited number of "stream descriptions":

``` xsd
<xs:complexType name="streams">
  <xs:sequence>
    <xs:element maxOccurs="unbounded" minOccurs="0" name="stream" type="streamType"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="streamType">
  <xs:all>
      <xs:element minOccurs="0" maxOccurs="1" name="name" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="dataType" type="dataType" />
      <xs:element minOccurs="1" maxOccurs="1" name="storageType" type="storageType" />
      <xs:element minOccurs="1" maxOccurs="1" name="number" type="xs:long"/>
  </xs:all>
</xs:complexType>

<xs:simpleType name="dataType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="MRAcquisition"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="storageType">
  <xs:restriction base="xs:string">
      <xs:enumeration value="ushort"/>
      <xs:enumeration value="short"/>
      <xs:enumeration value="uint"/>
      <xs:enumeration value="int"/>
      <xs:enumeration value="float"/>
      <xs:enumeration value="double"/>
      <xs:enumeration value="cxfloat"/>
      <xs:enumeration value="cxdouble"/>
  </xs:restriction>
</xs:simpleType>
```

Example:

``` xml
...
<streams>
  <stream>
    <name>k-space</name>
    <dataType>MRAcquisition</dataType>
    <storageType>cxfloat</storageType>
    <number>0</number>
  </stream>
  <stream>
    <name>ECG</name>
    <dataType>TODO: how to enumerate data types?</dataType>
    <storageType>float</storageType>
    <number>2</number>
  </stream>
</streams>
...
```
### Acquisition Header

The fixed-layout `Acquisition` header structure acquires two new fields: `storage_type`, which holds the value of an enumerated numeric type, and `stream_number`, which describes which stream this acquisition is a member of. These fields are located immediately after the `version` field.
### Acquisition Implementation

To account for acquisition data of varying storage types, the `Acquisition` class is now templated, similar to the `Image` class.
### HDF5 Dataset Implementation

All Acquisitions are currently stored in a dataset's  "data" path in an HDF5 file. This will change so that each stream is its own path (its number) inside the "data" path, e.g.

```
/dataset
  /data
    /0
    /1
    /2
    ...
```

This means the definition of `numberOfAcquisitions`, `readAcquisition`, and `appendAcquisition` functionality must change. One possible change is simply the addition of a `stream_number` parameter to each of these functions. The "user" is responsible for accessing the dataset's XML header to determine _which_ stream he/she is interested in.

A lookup table of all acquisition-like entities will also be added to the dataset. This tells the user which stream contains the **n**th entitity, and at what index in that stream.
## Questions
- How do we distinguish between MR Acquisitions with attached trajectories and other types of acquisitions/wave forms?
- What role does the "lookup table" play in the Dataset C++ API?

**Comment by hansenms** [comment]
Here are some thoughts.

I think the storage layout should be:

    /dataset
      /data
        /idx
        /0
        /1
        /2
        ...

The `idx` variable should be a table:

    | id | stream | index |
    | 0 |     0       |   0     |
    | 1 |     1       |   0     |
    | 2 |     0       |   1     |
    | 3 |     1       |   1     |
               ....
The `id` is not really needed, but included here for completeness. 

The `readAcquisition`, etc. could simply have an optional `stream` parameter which defaults to `-1`. If it is smaller than `0`, `readAcquisition` would read from the `idx` array and look up appropriate stream and index and then get the acquisition from there. If is `0` or larger, it will read from a specific stream. 

We have to think about the templatation of `Image` and `Acquisition`, since it would mean that the `readAcquisition` etc. function are also templated and that might have some ripple effects.

**Comment by naegelejd** [comment]
I understand the purpose of the lookup table but I think the `readAcquisition` function you suggest confuses the idea of an "acquisition number". Does an acquisition number **n** correspond to the **n**th entity in the dataset, or to the **n**th acquisition in its stream. If you intend to support both concepts, I think there should be two different acquisition reading functions: `readAcquisition` and `readAcquisitionFromStream`, or similar.

The `Image` and `NDArray` class have long been templated. Making the `Acquisition` class templated will definitely have rippling effects but it shouldn't be that bad. Example change in `recon_cartesian_2d.cpp`:
```diff
     // The number of channels is optional, so read the first line
-    ISMRMRD::Acquisition acq;
-    d.readAcquisition(0, acq);
+    ISMRMRD::Acquisition<complex_float_t> acq;
+    d.readAcquisition(0, 0, acq);
     uint16_t nCoils = acq.active_channels();
```
Is there a better idea than templating the `Acquisition` class?

Lastly, should all acquisitions continue to have an associated trajectory array?

**Comment by hansenms** [comment]
Well, I think the problem with the templating of the acquisitions is that we will be receiving a stream of these, so say first some MR data `ISMRMRD::Acquisition<complex_float_t>` then maybe some waveform `ISMRMRD::Acquisition<float>`. Maybe we need some sort of AcquisitionContainer concept that can then be cast to one or the other type, giving the user the ability to receive a stream of these generically and then check what type it is and react?
