### ISSUE TITLE
C-API blocking 2.x changes

### ISSUE THREAD

**Issue by naegelejd** [ismrmrd/ismrmrd#38]
I'm having issues extending the ISMRMRD implementation using the C API. Example:

I want to add an `idx` or `index` path to the dataset, along with numeric paths for each stream:

```
/dataset/
    /data/
        /idx
        /0
        /1
        ...
```

The [current function](https://github.com/ismrmrd/ismrmrd/blob/578ccf1a573f63547b28178757a7e9a6e92df3c8/libsrc/dataset.c#L73-L97) for making paths takes a single `const char*` tail, allocates a buffer using `malloc`, appends the tail to the dataset's `groupname`, and returns it. This is not very extendable and the buffer returned on every call must be `free`d, which is prone to error in functions where errors can cause early exits.

**Comment by hansenms** [comment]
I have to be honest, I really don't like the C API. Lots of memory problems here and there. It may just be a C thing, but it seems to be really error prone. 

What do you think we should do?

**Comment by naegelejd** [comment]
It is error prone. I've fixed many easily-detected memory leaks but it's very difficult to check every possible control flow.

After working with more C++/C projects since @inati  started the C API, I've learned that the better solution would have been to wrap the C++ implementation with a C API, rather than vice-versa (e.g. LLVM C-API).

As far as I can remember, the motivation for writing a C API was to make it more easily wrapped for other languages like Python. This hasn't been necessary since @inati changed `ismrmrd-python` to use `ctypes` (for the better).

I think having a C API is great, but a non-goal. I propose swapping the roles of the C and C++ implementation, making the C++ implementation primary.

Reasons to change:

- The HDF5 C-API is very unwieldy compared to the C++ API.
- Windows C compatibility is currently annoying (all our C code is written in C89 for Windows to compile it).
- Significant number of memory issues (I've fixed many but surely not all of them).
- There currently **isn't** a C API for the XML header or Meta attributes (already implemented in C++).
- Since the C++ API is actually used much more than the C API, and the C++ API has its own logic on top of the C API, we need unit tests for **BOTH**.

Reasons not to change:

- Time to implement (I already started weeks ago, plus it was originally implemented in C++... non-issue).

Anything else?

**Comment by hansenms** [comment]
I hope I am not stepping on any toes, but I vote for removing the C API all together. To my knowledge it is not used. At the very least it should be a wrapper around the C++ API as you state so that we gain some robustness.

**Comment by inati** [comment]
I am not wedded to the C API.  One of the reasons we made it in the first place was because we thought that the Python wrappers would be easier. But we've ditched that approach so that is a non issue now.  There was also some business of thread safety on (Windows?), but I don't know what the deal is with that anymore either.  

Since we're going down this path, what compiler do we need to be able to support?  Can we do it without boost?

-Souheil

**Comment by naegelejd** [comment]
As of right now we don't need or use Boost for the core implementation. We use it for the unit tests and utilities and I'm using it heavily for an ISMRMRD Protocol demo I'm working on in my 2.x branch. It would be nice to use C++11 features in the core implementation, but we really only need to use C++98/03, which is covered by all major C++ compilers.

**Comment by inati** [comment]
Don't we need a mutex if we use the hdf5 c++ api?

**Comment by hansenms** [comment]
Depends on how you look at it, we can also just say that the API is not thread safe and the application needs a mutex unless compiled with c++11 in which case we can use std::mutex?

------
