### ISSUE TITLE
3D CSI and kspace_encode_step_0

### ISSUE THREAD

**Issue by inati** [ismrmrd/ismrmrd#42]
We need to add space_encode_step_0 to the encoding counters in the c-struct.  (It's already in the schema).  This would make 3D CSI much easier.

**Comment by inati** [comment]
This does not of course address the issue of HOW to describe 3D CSI in the XML header, it just gives a hook.

**Comment by hansenms** [comment]
Right, let's keep this on the list for ISMRMRD 2.x
