### ISSUE TITLE
test_create_dataset.m for GRAPPA

### ISSUE THREAD

**Issue by DANAJK** [ismrmrd/ismrmrd#51]
I am trying to modify the ISMRMRD Matlab example file `test_create_dataset.m` such that it can simulate a GRAPPA acquisition. 
I have added code, including setting the flags ACQ_IS_PARALLEL_CALIBRATION_AND_IMAGING and ACQ_IS_PARALLEL_CALIBRATION, and:
```
header.encoding.parallelImaging.accelerationFactor.kspace_encoding_step_1 = 2 ;
header.encoding.parallelImaging.accelerationFactor.kspace_encoding_step_2 = 1 ;
header.encoding.parallelImaging.calibrationMode = 'embedded' ;

header.userParameters.userParameterLong.name = 'EmbeddedRefLinesE1' ;
header.userParameters.userParameterLong.value = 28 ;
```

The generated ISMRMRD h5 file does not reconstruct with `gadgetron_ismrmrd_client` using the `Generic_Cartesian_Grappa.xml` config file. The first obvious sign of trouble is the message:
`WARNING [mri_core_coil_map_estimation.cpp:636] coil_map_Inati, CHA <=1`  (I have four coils in my simulation).

Any clues on what is required of the ISMRMRD file for it to be valid for a GRAPPA recon?

**Comment by xueh2** [comment]
Hi David,

I think what is required are ismrmrd acquisitionSystemInformation section and parallelImaging section in the encoding space.

The encoding space size and encoding limits must be accurate too.

Could you send the modified test_create_dataset.m? I can do some debug into the problem here.

regards

Hui Xue

________________________________

**Comment by DANAJK** [comment]
Thanks, 

My modified file is attached. Git hub will not allow attachment of a .m file, so please change the extension from .txt to .m
[test_create_undersampled_dataset.txt](https://github.com/ismrmrd/ismrmrd/files/288406/test_create_undersampled_dataset.txt)


David

**Comment by xueh2** [comment]
I fixed a few findings and made a pull request.  With this pull request,

I got the kspace like this:

[cid:image001.png@01D1B9D4.19601E70]

Is the kspace line index correct here?

Regards

Hui

**Comment by DANAJK** [comment]
Thanks,
Sorry, I cannot see the image.
David

**Comment by xueh2** [comment]
![image](https://cloud.githubusercontent.com/assets/7012710/15636554/fb115380-25d0-11e6-904b-59d7fa190367.png)

here is the image

**Comment by DANAJK** [comment]
The k-space I put into the ISMRMRD file should have no zero lines - it is supposed to be just the acquired data.

In my MATLAB code, `acqno` increases by 1 for each acquired line. Hence I think the following was wrong:
`acqblock.head.idx.kspace_encode_step_1(acqno) = acqno-1; `
and it should use the `Ysamp` array to index from the acquired line number to the corresponding k-space value:
`acqblock.head.idx.kspace_encode_step_1(acqno) = Ysamp(acqno)-1; `

(Note the naming of this header variable is a bit confusing as it is not a "step"?)

I have also had to make some changes where some flags get set:
```
    if ismember(Ysamp(acqno),Ysamp_ACS)
            if ismember(Ysamp(acqno),Ysamp_u)
                % both calibration and part of the undersampled pattern
                acqblock.head.flagSet('ACQ_IS_PARALLEL_CALIBRATION_AND_IMAGING', acqno)
            else
                % in ACS block but not part of the regular undersampling
                % pattern Ysamp_u
                acqblock.head.flagSet('ACQ_IS_PARALLEL_CALIBRATION', acqno) ;
            end
        end
```
Note I assume that when setting the flag, the argument passed is the acquisition number and not the k-space value (ie `acqno` and not `Ysamp(acqno) `)

Unfortunately after making these changes, I still do not get the h5 file to reconstruct through gadgetron. However, I have not included the other changes that you mentioned because I cannot see them - perhaps the pull request has not come through yet?

[test_create_undersampled_dataset.txt](https://github.com/ismrmrd/ismrmrd/files/289439/test_create_undersampled_dataset.txt)

**Comment by hansenms** [comment]
I have merged the changes just now. Please check again.

**Comment by xueh2** [comment]
Now this works on mine

![image](https://cloud.githubusercontent.com/assets/7012710/15651312/bbc626c0-264c-11e6-8407-4ab70229bdbd.png)

Please use this xml. Since there are only 4 channels, the coil compression thres should be reduced.


[Generic_Cartesian_Grappa.xml.txt](https://github.com/ismrmrd/ismrmrd/files/289668/Generic_Cartesian_Grappa.xml.txt)

**Comment by DANAJK** [comment]
It works for me too now. Thanks for all your help. 

I attach here a tidied up file that you might want to put in the ismrmrd\examples\matlab folder (after removing the .txt extension):

[test_create_undersampled_dataset.m.txt](https://github.com/ismrmrd/ismrmrd/files/289843/test_create_undersampled_dataset.m.txt)

**Comment by hansenms** [comment]
Do you want to set up a pull request with the example. That way you get "credit" (or blame depending on your point of view) for the code.

------
