### ISSUE TITLE
Noise Handling

### ISSUE THREAD

**Issue by DANAJK** [ismrmrd/ismrmrd#54]
Is there any documentation, or examples, of how noise information is passed to Gadgetron via ISMRMRD? The context of this is trying to understand how GRAPPA reconstructions work in the Gadgetron.

**Comment by xueh2** [comment]
Here are the noise handling logic currently implemented:


a)      If an incoming data has no dependent noise scan, the build in noise readout lines will be used by the NoiseAdjust gadget for prewhitening (e.g. in VB17)

b)      If an incoming scan has dependent noise scan, the NoiseAdjust gadget will first go to search whether noise covariance matrix has been precomputed and stored (in linux /tmp/gadgetron folder, in windows, c:/temp/gadgetron), e.g. in VD and VE lines



If there are stored noise covariance matrix, it will be read in and used for prewhitening

If not, building noise will be used if any

c)       On the scanner, IceGadgetron will check whether a gadgetron scan has dependent noise scan. If yes, the noise scan will be found from raid and sent to gadgetron side before sending the imaging scan. Therefore, when gadgetron received its first imaging scan readout, the noise covariance matrix has already been stored.

**Comment by DANAJK** [comment]
In case a), to simulate a scan with noise built in, is the following correct MATLAB where `noise level_sd` is the standard deviation of Normally distributed, zero mean noise?

```
noiseblock = ismrmrd.Acquisition(1) ;
noiseblock.head.version(:) = 1;
noiseblock.head.number_of_samples(:) = nX;
noiseblock.head.active_channels(:) = nCoils;
noiseblock.head.flagSet('ACQ_IS_NOISE_MEASUREMENT', 1); 
 
knoise = complex(zeros([nX nCoils])) ;
knoise = add_noise(knoise, noiselevel_sd) ;

noiseblock.data{1} = knoise ;
dset.appendAcquisition(noiseblock) ;
```

**Comment by xueh2** [comment]
The noise adding code looks correct to me. Gadgetron should pick up this noise scan and compute covariance matrix on it.

One way to do further testing to generate colored noise by applying a known noise covariance matrix. Then gadgetron should give a good estimate of this covariance matrix.

**Comment by hansenms** [comment]
Closing since it has been sitting for....well years.
