### ISSUE TITLE
Timestamp temporal resolution

### ISSUE THREAD

**Issue by DANAJK** [ismrmrd/ismrmrd#66]
Following discussion about the temporal resolution of the timestamps in release 2.0, I understand the following about PET time of flight data:

Typical PET list mode time stamps are only in milliseconds. For time of flight, the data is usually indexed by bin, where the bin represents some range of detector times in the pico second region. I assume thIs bin is essentially a distance along a line of response, and lines of response are effectively lumped into millisecond groups.  
So, it would seem that at least for now, a nano second resolution for the time stamp would be OK.

**Comment by hansenms** [comment]
Thanks for checking up on this. We will forge ahead with nano seconds then. Should I close this issue?
