### ISSUE TITLE
Systematic tagging of new releases

### ISSUE THREAD

**Issue by ghisvail** [ismrmrd/ismrmrd#71]
Commit https://github.com/ismrmrd/ismrmrd/commit/f12b69e526e3aa2434dba8ea3f63eec011b5b895 bumped the version number of `ismrmrd`. Please consider systematically tagging new releases in the future.

Same comment applies to `gadgetron` (last tag was for 3.8.x series, whereas the software is not at 3.14.x). Probably not worth filing a separate issue for it, since you are the lead dev of both projects.

Thanks,
Ghis

**Comment by hansenms** [comment]
We don't make releases right now.
