### ISSUE TITLE
FTBFS with HDF5 1.10 due to a change of fileid type

### ISSUE THREAD

**Issue by ghisvail** [ismrmrd/ismrmrd#73]
Just forwarding an [issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841959) we had with compilation of `ismrmrd` on Debian following the transition of the archive to hdf5 v1.10.

Essentially, it all comes down to a change in the HDF5 API regarding the returned type of `H5Fopen`, which is no longer an `int` but a `long long` in v1.10. Actually, HDF5 encapsulates this return type to a `hid_t`, and the patch proposed by Gilles uses this type for `ISMRMRD_Dataset.fileid` which eventually fixes the problem.

Are you happy with this change? If so, I can forward Gilles' patch in a subsequent PR.

**Comment by hansenms** [comment]
@ghisvail sorry for the slow response here. I also need to deal with the other PR you put up. 

But yes, sounds like a reasonable change. Would that be backwards compatible with 1.8?

**Comment by ghisvail** [comment]
> @ghisvail sorry for the slow response here. I also need to deal with the other PR you put up. 

No problem.

> Would that be backwards compatible with 1.8?

Gilles already pushed the change in the archive which still has 1.8 and the build and test suite ran fine. Since `hid_t` was 32-bit on HDF5 1.8, the change remains compatible with the old signature of `ISMRMRD_Dataset`.

**Comment by hansenms** [comment]
Great, thanks! I will watch for the PR then.
