### ISSUE TITLE
C99 support on VS2013 and VS2015

### ISSUE THREAD

**Issue by KrisThielemans** [ismrmrd/ismrmrd#82]
ismrmrd.h contains assumptions that if _MSC_VER is defined, it's a really old version, e.g.

```
#ifndef __cplusplus
#ifdef _MSC_VER /* MS C compiler */
typedef int bool;
#define false 0
#define true 1
#else /* C99 compiler */
#include <stdbool.h>
#endif /* _MSC_VER */
#endif /* __cplusplus */
```
I think it would be better to replace these checks with 
```
#if defined(__STDC__) && __STDC_VERSION__ >= 199901L
```
we could test this with VS2013 and 2015, not older though.

As an example, we recently had a case with VS2013 where the above caused a compilation failure (as bool was a predefined type), but we cannot reproduce this (it probably had to do with versions of HDF5, boost etc). Presumably stdbool was included before ismrmrd.h or so.

we could make a pull-request with these changes if you like.

**Comment by hansenms** [comment]
It's a bit unclear what you mean by you cannot reproduce it? Are you proposing a fix to a problem that cannot be reproduced?

**Comment by KrisThielemans** [comment]
:-; 

we were in the middle of figuring out why things didn't work and were changing stuff around all the time. So I cannot remember the exact configuration where we had that particular build error.

The following simply code doesn't compile on VS2015
```
#include <stdbool.h>
#include "ismrmrd/ismrmrd.h"

int main()
{
  return 0;
}
 ```
start of error messages
````
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		identifier "size_t" is undefined	ismrmrd-test	c:\Users\krisf\Documents\devel\install-VC\include\ismrmrd\ismrmrd.h	129	
Error (active)		invalid combination of type specifiers	ismrmrd-test	c:\Users\krisf\Documents\devel\install-VC\include\ismrmrd\ismrmrd.h	63	
```
Of course, it does compile with including stdbool.h.

It turns out that VS 2015 doesn't define __STDC__VERSION__ so the above suggestion doesn't work, but I can fix this by changing l62 ismrmrd.h to
```
#if _MSC_VER < 1800
```
I can submit a PR if you like.

**Comment by hansenms** [comment]
If you actually set up your project with cmake and use find_package, does it work? We build with VS2015 all the time and have no issues.

**Comment by KrisThielemans** [comment]
The above test program was compiled via CMake yes, but it doesn't really matter in my opinion as CMake doesn't set any specific flags.

Just to confirm: VS2015 will compile ismrmrd without this fix (and our CCPPETMR software as well), at least under most circumstances (as I said above, it seems to depend on what some external libraries you have installed).

It seems a harmless fix to me. The change will not affect anything else than VS 2013 or higher. However, at present we can live without it, so as you prefer.

**Comment by hansenms** [comment]
There is no such thing as a harmless fix when it comes to Visual Studio. We should fix if it is a bug that causes problems. If not, let's leave it alone.

**Comment by KrisThielemans** [comment]
as you prefer. feel free to close then

**Comment by hansenms** [comment]
I'll keep it open. Open up a PR and I will have @xueh2 test it.
