### ISSUE TITLE
throwing in destructors is dangerous

### ISSUE THREAD

**Issue by KrisThielemans** [ismrmrd/ismrmrd#83]
when compiling with VS2015 I get warnings like
```
2>C:\Users\krisf\Documents\devel\ismrmrd\libsrc\ismrmrd.cpp(103): warning C4297: 'ISMRMRD::Acquisition::~Acquisition': function assumed not to throw an exception but does
2>  C:\Users\krisf\Documents\devel\ismrmrd\libsrc\ismrmrd.cpp(103): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
```
Reading-up a bit, it seems this is dangerous, see e.g.
http://stackoverflow.com/questions/130117/throwing-exceptions-out-of-a-destructor

**Comment by hansenms** [comment]
Should probably be fixed. Feel free to do so.

**Comment by KrisThielemans** [comment]
I'm afraid I don't know enough about ismrmrd (or infact C++) to fix this one. sorry

**Comment by hansenms** [comment]
OK, we will put it on the list. This library is a about to get an overhaul anyway.
