### ISSUE TITLE
Problem with ISMRMRD installation on Mac

### ISSUE THREAD

**Issue by Kuslaw** [ismrmrd/ismrmrd#86]
Hi,

Sorry to bother you, but I wanted to start my adventure with Gadgetron and I got stuck with an issue related to the installation of ISMRMRD software package on my Mac. My Mac runs under El Capitan. To install ISMRMRD, GADGETRON, and all other stuffs I follow the instruction provided on the Internet. Unfortunately, each time when I come to the installation of the ISMRMRD I get the same error, after I type "make", which is the following:
Scanning dependencies of target ismrmrd
[  3%] Building C object CMakeFiles/ismrmrd.dir/libsrc/ismrmrd.c.o
[  6%] Building CXX object CMakeFiles/ismrmrd.dir/libsrc/ismrmrd.cpp.o
[ 10%] Building CXX object CMakeFiles/ismrmrd.dir/libsrc/xml.cpp.o
[ 13%] Building CXX object CMakeFiles/ismrmrd.dir/libsrc/meta.cpp.o
[ 16%] Building C object CMakeFiles/ismrmrd.dir/libsrc/dataset.c.o
In file included from /Users/slawek/ismrmrd/libsrc/dataset.c:14:
In file included from /Users/slawek/ismrmrd/include/ismrmrd/dataset.h:11:
/Users/slawek/ismrmrd/include/ismrmrd/ismrmrd.h:63:13: error: cannot combine
      with previous 'int' declaration specifier
typedef int bool;
            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include/stdbool.h:31:14: note: 
      expanded from macro 'bool'
#define bool _Bool
             ^
In file included from /Users/slawek/ismrmrd/libsrc/dataset.c:14:
In file included from /Users/slawek/ismrmrd/include/ismrmrd/dataset.h:11:
/Users/slawek/ismrmrd/include/ismrmrd/ismrmrd.h:63:1: warning: typedef requires
      a name [-Wmissing-declarations]
typedef int bool;
^~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/ismrmrd.dir/libsrc/dataset.c.o] Error 1
make[1]: *** [CMakeFiles/ismrmrd.dir/all] Error 2
make: *** [all] Error 2
Has anyone of you had such problem and found a solution?

I'll be really grateful for help.

Kind regards,
Kuslaw

**Comment by hansenms** [comment]
Sorry, I don't have a Mac with El Capitan on. Problem seems related to this line:

https://github.com/ismrmrd/ismrmrd/blob/master/include/ismrmrd/ismrmrd.h#L63

which should not be compiled on the Mac. 

Could you change:

```
#ifndef __cplusplus
#if _MSC_VER < 1800 /* old MS C compiler */
typedef int bool;
#define false 0
#define true 1
#else /* C99 compiler */
#include <stdbool.h>
#endif /* _MSC_VER */
#endif /* __cplusplus */
```

to 

```
#ifndef __cplusplus
#if _MSC_VER < 1800 /* old MS C compiler */
#pragma message("In MS code")
typedef int bool;
#define false 0
#define true 1
#else /* C99 compiler */
#include <stdbool.h>
#endif /* _MSC_VER */
#endif /* __cplusplus */
```

Do a make clean, then make and post the output.

If it prints the `In MS code` message, please try:

```
#ifndef __cplusplus
#if _MSC_VER  /* old MS C compiler */
typedef int bool;
#define false 0
#define true 1
#else /* C99 compiler */
#include <stdbool.h>
#endif /* _MSC_VER */
#endif /* __cplusplus */
```

And try again. 

Thanks,
Michael

**Comment by Kuslaw** [comment]
Hi Michael,

Many thanks for your quick response to my query. It was very helpful. The second option worked in my case.

I received many warnings during the installation of Gadgetron. Would you like to have a look at them or you're aware of them already? I'm going to test Gadgetron on my Mac.

Kind regards,
Kuslaw

**Comment by hansenms** [comment]
I would rather have you fix the warnings and put up a pull request. A list of the warnings is not that helpful since I don't have the tools to mitigate. 

@KrisThielemans your PR regarding the `_MSC_VER` is causing problems on the Mac, would you care to comment? We may have to roll that back. Could you remind why we put that in again?

**Comment by KrisThielemans** [comment]
I guess I misunderstood the C processor stuff when a variable is not defined. i did find that gcc says that in if statements "Identifiers that are not macros ...are all considered to be the number zero"

@Kuslaw would you be able to try

> #if defined(_MSC_VER) && (_MSC_VER < 1800)

**Comment by KrisThielemans** [comment]
created PR #87
