### ISSUE TITLE
Linking CXX shared library libismrmrd.so ... error

### ISSUE THREAD

**Issue by curtcorum** [ismrmrd/ismrmrd#95]
Hello All,
Having some issues with build from source of ismrmrd on ubuntu 14.04.
Doing this so I can build ge_to_ismrmrd.

cmake output (seems ok):

curt@sagan:~/src/ismrmrd/build$ cmake -D CMAKE_INSTALL_PREFIX=$ISMRMRD_HOME -D HDF5_USE_STATIC_LIBRARIES=yes -D CMAKE_EXE_LINKER_FLAGS=-lpthread ..
Building info application
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   program_options
-- FFTW3 UNIX libraries: /usr/lib/x86_64-linux-gnu/libfftw3f.so
FFTW3 and Boost Found... building utilities
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   unit_test_framework
CPACK_PACKAGING_INSTALL_PREFIX: /home/curt/src/ismrmrd
-- Found CPack generators: DEB
-- Configuring done
-- Generating done
-- Build files have been written to: /home/curt/src/ismrmrd/build

make install problem:

curt@sagan:~/src/ismrmrd/build$ make install
[  4%] Building C object CMakeFiles/ismrmrd.dir/libsrc/ismrmrd.c.o
[  9%] Building CXX object CMakeFiles/ismrmrd.dir/libsrc/ismrmrd.cpp.o
[ 13%] Building CXX object CMakeFiles/ismrmrd.dir/libsrc/xml.cpp.o
[ 18%] Building CXX object CMakeFiles/ismrmrd.dir/libsrc/meta.cpp.o
[ 22%] Building C object CMakeFiles/ismrmrd.dir/libsrc/dataset.c.o
[ 27%] Building CXX object CMakeFiles/ismrmrd.dir/libsrc/dataset.cpp.o
[ 31%] Building CXX object CMakeFiles/ismrmrd.dir/libsrc/pugixml.cpp.o
Linking CXX shared library libismrmrd.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libhdf5.a(H5.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libhdf5.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libismrmrd.so.1.3.3] Error 1
make[1]: *** [CMakeFiles/ismrmrd.dir/all] Error 2
make: *** [all] Error 2

this occurs even when CMakeCache.txt has been edited with:
 
curt@sagan:~/src/ismrmrd/build$ cat CMakeCache.txt | grep fPIC
CMAKE_CXX_FLAGS:STRING=-fPIC
CMAKE_C_FLAGS:STRING=-fPIC

Any thoughts?

thanks,
Curt

**Comment by hansenms** [comment]
Ubuntu 14.04 is no longer a supported target platform.

The problem is not the linking settings on ismrmrd, it is libhdf5.a, which is a static library and you need the dynamically linked one (*.so).
