### ISSUE TITLE
ISMRMRD build linking against wrong HDF5 and including extra symbols

### ISSUE THREAD

**Issue by roopchansinghv** [ismrmrd/ismrmrd#97]
I am working on updating the ge_to_ismrmrd converter to work with the vendor's current SDK, and am running into an issue with the build process not linking cleanly to the static HDF5 libraries that come with the vendor's SDK.

I go through the process as detailed here:

   https://github.com/ismrmrd/ge_to_ismrmrd/blob/master/README.md

and set HDF5_ROOT to point to the HDF libraries distributed with GE's SDK:

   setenv   HDF5_ROOT   $SDKTOP/include/recon/3p/Linux/hdf5-1.8.12_dev_linux64/

and run the ISMRMRD cmake configure to use these:

   cmake -D CMAKE_INSTALL_PREFIX=$ISMRMRD_HOME -D HDF5_USE_STATIC_LIBRARIES=yes -D CMAKE_EXE_LINKER_FLAGS=-lpthread ..

However, during the ISMRMRD build process, I get message of undefined references, that I cannot find the vendor's static SDK, but are in the system's dynamic libraries.  The build log is attached, output from make VERBOSE=1

   [build.log](https://github.com/ismrmrd/ismrmrd/files/1369096/build.log)

Any ideas as to what I missed, or am not doing?  For platform reference, this is in an openSUSE Linux 42.3 container, with GCC 4.8.5

**Comment by curtcorum** [comment]
I have had similar issues, although on Ubuntu 16.04 which is not a supported orchestra_sdk platform.

**Comment by roopchansinghv** [comment]
Cmake seems unable to choose a particular version of HDF5, and seems to pick the latest version on the system.  Removing the version of HDF5 supplied by the OS resolved this issue.
