### ISSUE TITLE
How to remove all data acquisitions from an ISMRMRD file

### ISSUE THREAD

**Issue by chandnisp77** [ismrmrd/ismrmrd#99]
Hi all,
I am creating an `ISMRMRD h5` file with only header xml from a `gui` application and later on in another exe I fill data acquisitions (data part of h5) from a data simulator. As part of testing data acquisition side, I have to use the same h5 file for filling data node of `ISMRMRD`. 
Is there a way to programatically remove all existing data acquisitions before pushing new data? Similar to `Delete` option in right click menu of data node in `HDFView` software? Currently i use this for deleting existing data acquisitions. One thing I noticed is that the size of h5 file does not change and it continues to grow in size even after deleting data nodes from h5 file. 

Thanks.

**Comment by dchansen** [comment]
Hi,

It is not possible to remove data from an h5 file, it is just flagged as deleted. Instead, what utilities like h5repack does is to make a new h5 set and copy only the non-flagged entries. 
Your best option is thus to remove the entries from the h5 file and use h5repack afterwards.
See [this discussion](https://stackoverflow.com/questions/447854/delete-or-update-a-dataset-in-hdf5) for details.

**Comment by chandnisp77** [comment]
Thanks for your comments.
